spring.application.name=caixinha
spring.datasource.url=jdbc:h2:mem:caixadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=pbe
spring.datasource.password=coisarada
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect